version: '3'

services:
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/sites-available/
      - wp-data:/var/www/html

    networks:
      - inception
    restart: always

  mariadb:
    build:
        context: ./
        dockerfile: ./requirements/mariadb/Dockerfile
    env_file: 
      - ./.env
    image: mariadb
    container_name: mariadb
    volumes:
        - db-data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build:
        context: ./
        dockerfile: ./requirements/wordpress/Dockerfile
    env_file: 
      - ./.env
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html/
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: always

volumes:
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /home/mlalouli/data/wp
  db-data:
    driver_opts:
      o: bind
      type: none
      device: /home/mlalouli/data/db


networks:
  inception:
    driver: bridge
